version: '3.9'
services:
  pgsql:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'pgsql'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: tools-manager

  adminer:
    image: adminer
    container_name: 'adminer'
    restart: always
    ports:
      - 8080:8080

  redis: 
    image: redis
    ports:
      - 6379:6379
    volumes:
      - .docker/redis:/data
  app:
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
           - ./:/app
      env_file: ./.env.example
      container_name: 'tools_manager_api'
      ports:
        - 3333:3333
      depends_on:
        - pgsql
        - redis